version: '3.4'
 
services:
  daprunleashed-api:
    image: ${DOCKER_REGISTRY-}daprunleashedapi
    ports:
      - "16002:443"
    depends_on:
      - placement
    build:
      context: ./source/DaprUnleashed.IngestionService
      dockerfile: Dockerfile
    networks:
      - dapr-unleashed

 
  daprunleashed-api-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "daprunleashed-api",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-resources-path", "/components"
     ]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - daprunleashed-api
    network_mode: "service:daprunleashed-api"
 
  daprunleashed-extractionservice:
    ports:
      - "16004:80"
    image: ${DOCKER_REGISTRY-}daprunleashedextractionservice
    depends_on:
      - placement
    build:
      context: ./source/DaprUnleashed.ExtractionService
      dockerfile: Dockerfile
    networks:
      - dapr-unleashed
 
  daprunleashed-extractionservice-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "daprunleashed-extractionservice",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "-resources-path", "/components"
     ]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - daprunleashed-extractionservice
    network_mode: "service:daprunleashed-extractionservice"
 
  daprunleashed-transformationservice:
    ports:
      - "16005:80"
    image: ${DOCKER_REGISTRY-}daprunleashedtransformationservice
    build:
      context: ./source/DaprUnleashed.TransformationService
      dockerfile: Dockerfile
    networks:
      - dapr-unleashed
  daprunleashed-transformationservice-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "daprunleashed-transformationservice",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-resources-path", "/components"
     ]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - daprunleashed-transformationservice
    network_mode: "service:daprunleashed-transformationservice"
 
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
 
  dapr-dashboard:
    image: "daprio/dashboard:latest"
    command: [ "--docker-compose=true", 
      "--components-path=/components", 
      "--config-path=/configuration", 
      "--docker-compose-path=/docker-compose.yml"]
    ports:
      - "8080:8080"
    volumes:
      - "./components/:/components"
      - "./docker-compose.yml:/docker-compose.yml"
    networks:
      - dapr-unleashed
 
 
  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "5411:9411"
    networks:
      - dapr-unleashed
 
networks:
    dapr-unleashed: