version: '3.4' 

services:
  daprunleashed.api:
    image: ${DOCKER_REGISTRY-}daprunleashedapi
    environment:
        "DaprUnleashedKeyVault": "https://demo-daprunleashed-kv.vault.azure.net/"
        "AZURE_TENANT_ID": "035b20a1-9b1d-4c2f-86f0-d872d8b23919"
        "AZURE_CLIENT_ID": "d1c07fd0-081c-4f07-85c2-c4d0f9ab8fd5"
        "AZURE_CLIENT_SECRET": "omk8Q~vwPsTuVHkLXeUzRD1xmUkq-VeXvkybMbm8"
    build:
      context: .
      dockerfile: source/DaprUnleashed.IngestionService/Dockerfile

  daprunleashed.transformationservice:
    image: ${DOCKER_REGISTRY-}daprunleashedtransformationservice
    environment:
        "DaprUnleashedKeyVault": "https://demo-daprunleashed-kv.vault.azure.net/"
        "AZURE_TENANT_ID": "035b20a1-9b1d-4c2f-86f0-d872d8b23919"
        "AZURE_CLIENT_ID": "d1c07fd0-081c-4f07-85c2-c4d0f9ab8fd5"
        "AZURE_CLIENT_SECRET": "omk8Q~vwPsTuVHkLXeUzRD1xmUkq-VeXvkybMbm8"
    build:
      context: .
      dockerfile: source/DaprUnleashed.TransformationService/Dockerfile


  daprunleashed.extractionservice:
    image: ${DOCKER_REGISTRY-}daprunleashedextractionservice
    environment:
        "DaprUnleashedKeyVault": "https://demo-daprunleashed-kv.vault.azure.net/"
        "AZURE_TENANT_ID": "035b20a1-9b1d-4c2f-86f0-d872d8b23919"
        "AZURE_CLIENT_ID": "d1c07fd0-081c-4f07-85c2-c4d0f9ab8fd5"
        "AZURE_CLIENT_SECRET": "omk8Q~vwPsTuVHkLXeUzRD1xmUkq-VeXvkybMbm8"
    build:
      context: .
      dockerfile: source/DaprUnleashed.ExtractionService/Dockerfile
