version: '3.4'
 
services:
  daprunleashed-api:
    image: ${DOCKER_REGISTRY-}daprunleashedapi
    ports:
      - "50001:50001" # Dapr instances communicate over gRPC so we need to expose the gRPC port
      - "16001:80"
      - "16002:443"
    depends_on:
      - placement
    build:
      context: .
      dockerfile: ./source/DaprUnleashed.IngestionService/Dockerfile
    networks:
      - dapr-unleashed

 
  daprunleashed-api-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "daprunleashed-api",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-resources-path", "/components",
     "-config", "/configuration/config.yaml"
     ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
        - "./configuration/:/configuration" # Mount configuration
    depends_on:
      - daprunleashed-api
    network_mode: "service:daprunleashed-api" # Attach the sidecar to the app network namespace to enable communication over localhost
 
  daprunleashed-extractionservice:
    ports:
      - "50002:50001"
      - "16003:80"
      - "16004:443"
    image: ${DOCKER_REGISTRY-}daprunleashedextractionservice
    depends_on:
      - placement
    build:
      context: .
      dockerfile: ./source/DaprUnleashed.ExtractionService/Dockerfile
    networks:
      - dapr-unleashed
 
  daprunleashed-extractionservice-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "daprunleashed-extractionservice",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-resources-path", "/components",
     "-config", "/configuration/config.yaml"
     ]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - daprunleashed-extractionservice
    network_mode: "service:daprunleashed-extractionservice"
 
  daprunleashed-transformationservice:
    ports:
      - "50003:50001"
      - "16005:80"
      - "16006:443"
    image: ${DOCKER_REGISTRY-}daprunleashedtransformationservice
    build:
      context: .
      dockerfile: ./source/DaprUnleashed.TransformationService/Dockerfile
    networks:
      - dapr-unleashed
  daprunleashed-transformationservice-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "daprunleashed-transformationservice",
     "-app-port", "80",
     "-placement-host-address", "placement:50006",
     "-resources-path", "/components",
     "-config", "/configuration/config.yaml"
     ]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - daprunleashed-transformationservice
    network_mode: "service:daprunleashed-transformationservice"
 
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
 
  dapr-dashboard:
    image: "daprio/dashboard:latest"
    command: [ "--docker-compose=true", 
      "--components-path=/components", 
      "--config-path=/configuration", 
      "--docker-compose-path=/docker-compose.yml"]
    ports:
      - "8080:8080"
    volumes:
      - "./components/:/components"
      - "./docker-compose.yml:/docker-compose.yml"
      - "./configuration/:/configuration"
    networks:
      - dapr-unleashed
 
 
  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"
    networks:
      - dapr-unleashed
 
networks:
    dapr-unleashed: