version: '3.4'
 
services:
  daprunleashed-api:
    image: ${DOCKER_REGISTRY-}daprunleashedapi
    depends_on:
      - placement
    build:
      context: .
      dockerfile: source/DaprUnleashed.IngestionService/Dockerfile

 
  daprunleashed-api-dapr:
    image: "daprio/daprd:edge"
    command: [
     "./daprd",
     "-app-id", "daprunleashed-api",
     "-app-port", "80",
     "-dapr-http-port", "3501",
     "-dapr-grpc-port", "50001",
     "-placement-host-address", "placement:50006",
     "--resources-path", "/components",
     "-config", "/configuration/collector-config.yaml"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - daprunleashed-api
    network_mode: "service:daprunleashed-api"
 
  daprunleashed-extractionservice:
    image: ${DOCKER_REGISTRY-}daprunleashedextractionservice
    depends_on:
      - placement
    build:
      context: .
      dockerfile: source/DaprUnleashed.ExtractionService/Dockerfile
 
  daprunleashed-extractionservice-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "daprunleashed-extractionservice",
     "-app-port", "80",
     "-dapr-http-port", "3502",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "--resources-path", "/components",
     "-config", "/configuration/collector-config.yaml"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - daprunleashed-extractionservice
    network_mode: "service:daprunleashed-extractionservice"
 
  daprunleashed-transformationservice:
    image: ${DOCKER_REGISTRY-}daprunleashedtransformationservice
    depends_on:
      - placement
    build:
      context: .
      dockerfile: source/DaprUnleashed.TransformationService/Dockerfile

  daprunleashed-transformationservice-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "daprunleashed-transformationservice",
     "-app-port", "80",
     "-dapr-http-port", "3503",
     "-dapr-grpc-port", "50003",
     "-placement-host-address", "placement:50006",
     "--resources-path", "/components",
     "-config", "/configuration/collector-config.yaml"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - daprunleashed-transformationservice
    network_mode: "service:daprunleashed-transformationservice"
 
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
 
  dapr-dashboard:
    image: "daprio/dashboard:latest"
    command: [ "--docker-compose=true", 
      "--components-path=/components", 
      "--config-path=/configuration", 
      "--docker-compose-path=/docker-compose.yml" ]
    ports:
      - "8080:8080"
    volumes:
      - "./components/:/components"
      - "./docker-compose.yml:/docker-compose.yml"
 
 
  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "5411:9411"
 
  otel:
    image: otel/opentelemetry-collector-contrib-dev:latest
    command: [ "--config=/configuration/open-telemetry-collector-appinsights.yaml"]
    volumes:
     - "./configuration/:/configuration"
 