version: '3.4'

services:
  daprunleashed.api:
    image: ${DOCKER_REGISTRY-}daprunleashedapi
    environment:
        "DaprUnleashedKeyVault": "https://dapr-unleashed-keyv-dev.vault.azure.net/"
        "AZURE_TENANT_ID": "035b20a1-9b1d-4c2f-86f0-d872d8b23919"
        "AZURE_CLIENT_ID": "a3127704-7aea-4057-b15e-b75d78b3e0a8"
        "AZURE_CLIENT_SECRET": "SsK8Q~UGkohkKwLKF-9OCNj22j-ziamiPglwrb_3"
    build:
      context: .
      dockerfile: source/DaprUnleashed.IngestionService/Dockerfile

  daprunleashed.transformationservice:
    image: ${DOCKER_REGISTRY-}daprunleashedtransformationservice
    environment:
        "DaprUnleashedKeyVault": "https://dapr-unleashed-keyv-dev.vault.azure.net/"
        "AZURE_TENANT_ID": "035b20a1-9b1d-4c2f-86f0-d872d8b23919"
        "AZURE_CLIENT_ID": "a3127704-7aea-4057-b15e-b75d78b3e0a8"
        "AZURE_CLIENT_SECRET": "SsK8Q~UGkohkKwLKF-9OCNj22j-ziamiPglwrb_3"
    build:
      context: .
      dockerfile: source/DaprUnleashed.TransformationService/Dockerfile


  daprunleashed.extractionservice:
    image: ${DOCKER_REGISTRY-}daprunleashedextractionservice
    environment:
        "DaprUnleashedKeyVault": "https://dapr-unleashed-keyv-dev.vault.azure.net/"
        "AZURE_TENANT_ID": "035b20a1-9b1d-4c2f-86f0-d872d8b23919"
        "AZURE_CLIENT_ID": "a3127704-7aea-4057-b15e-b75d78b3e0a8"
        "AZURE_CLIENT_SECRET": "SsK8Q~UGkohkKwLKF-9OCNj22j-ziamiPglwrb_3"
    build:
      context: .
      dockerfile: source/DaprUnleashed.ExtractionService/Dockerfile

